on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: run one line script
        run: echo "Hello from GitHub actions!"
      - name: run multi line script
        run: |
          run: |
            echo "The current server time is $(date)"
            echo "`uname -a`"
